Update obsolete patch macro, Rebuild on gnutls
This change is motivated for rebuild of nut,
that depends on libusb-devel that pull neon that requieres older gnutls:

     --> 1:libusb-devel-0.1.4-3.el7.x86_64
    Error: Package: neon-0.30.0-3.el7.x86_64 (build)
           Requires: libgnutls.so.28()(64bit)

Rebuilding neon on updated gnutls is solving this issue.

Relate-to: XCPNG-3553
Origin: https://github.com/xcp-ng-rpms/neon/pull/1
Signed-off-by: Philippe Coval <philippe.coval@vates.tech>